---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: istioSidecar - metadata - name
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  istioSidecars.main:
    spec:
      egress:
        - hosts:
            - "./*"
tests:
  - it: name defaults to chart fullName
    asserts:
      - containsDocument:
          kind: Sidecar
          apiVersion: networking.istio.io/v1
          name: release-name
          any: true

  - it: name includes identifier when alwaysAppendIdentifierToResourceName is enabled
    set:
      global.alwaysAppendIdentifierToResourceName: true
    asserts:
      - containsDocument:
          kind: Sidecar
          apiVersion: networking.istio.io/v1
          name: release-name-main
          any: true

  - it: forceRename
    set:
      istioSidecars.main.forceRename: forceRename
    asserts:
      - containsDocument:
          kind: Sidecar
          apiVersion: networking.istio.io/v1
          name: forcerename
          any: true

  - it: prefix
    set:
      istioSidecars.main.prefix: prefix
    asserts:
      - containsDocument:
          kind: Sidecar
          apiVersion: networking.istio.io/v1
          name: prefix-release-name
          any: true

  - it: suffix
    set:
      istioSidecars.main.suffix: suffix
    asserts:
      - containsDocument:
          kind: Sidecar
          apiVersion: networking.istio.io/v1
          name: release-name-suffix
          any: true

  - it: multiple items
    set:
      istioSidecars.second:
        spec:
          egress:
            - hosts:
                - "./*"
    asserts:
      - containsDocument:
          kind: Sidecar
          apiVersion: networking.istio.io/v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: Sidecar
          apiVersion: networking.istio.io/v1
          name: release-name-second
          any: true
