---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: istioDestinationRule - metadata - name
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  istioDestinationRules.main:
    spec:
      host: test-service
tests:
  - it: name defaults to chart fullName
    asserts:
      - containsDocument:
          kind: DestinationRule
          apiVersion: networking.istio.io/v1
          name: release-name
          any: true

  - it: name includes identifier when alwaysAppendIdentifierToResourceName is enabled
    set:
      global.alwaysAppendIdentifierToResourceName: true
    asserts:
      - containsDocument:
          kind: DestinationRule
          apiVersion: networking.istio.io/v1
          name: release-name-main
          any: true

  - it: forceRename
    set:
      istioDestinationRules.main.forceRename: forceRename
    asserts:
      - containsDocument:
          kind: DestinationRule
          apiVersion: networking.istio.io/v1
          name: forcerename
          any: true

  - it: prefix
    set:
      istioDestinationRules.main.prefix: prefix
    asserts:
      - containsDocument:
          kind: DestinationRule
          apiVersion: networking.istio.io/v1
          name: prefix-release-name
          any: true

  - it: suffix
    set:
      istioDestinationRules.main.suffix: suffix
    asserts:
      - containsDocument:
          kind: DestinationRule
          apiVersion: networking.istio.io/v1
          name: release-name-suffix
          any: true

  - it: multiple items
    set:
      istioDestinationRules.second:
        spec:
          host: other-service
    asserts:
      - containsDocument:
          kind: DestinationRule
          apiVersion: networking.istio.io/v1
          name: release-name-main
          any: true
      - containsDocument:
          kind: DestinationRule
          apiVersion: networking.istio.io/v1
          name: release-name-second
          any: true
